routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function(){
    Route::get('/', App\Http\Controllers\DashboardController::class)->name('dashboard');
    Route::get('/transaction/{transaction}/export', App\Http\Controllers\ExportTransactionController::class)->name('transaction.export');
    Route::get('/transaction/{transaction}/print', App\Http\Controllers\PrintTransactionController::class)->name('transaction.print');
    Route::resource('transaction', App\Http\Controllers\TransactionController::class);
});

Route::middleware(['auth', 'admin'])->group(function(){
    Route::resource('product', App\Http\Controllers\ProductController::class);
    Route::resource('user', App\Http\Controllers\UserController::class);
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = 'master_barang';

    public function scopeFilter($query, array $filters)
    {
        $query->when($filters['nama_barang'] ?? false, function($query, $nama_barang) {
            $query->where('nama_barang', 'like', '%' . $nama_barang . '%');
        });

        $query->when($filters['harga_satuan'] ?? false, function($query, $harga_satuan, $operator) {
            $query->where('harga_satuan', $operator, $harga_satuan);
        });
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::query()
            ->when(request()->has('nama_barang') ?? false, function($query) {
                $query->where('nama_barang', 'like', '%' . request('nama_barang') . '%');
            })
            ->when(request()->has('harga_satuan') AND ! empty(request('harga_satuan')) ?? false, function($query) {
                $query->where('harga_satuan', request('operator'), request('harga_satuan'));
            })
            ->latest()
            ->get();

        return view('product.index', [
            'products' => $products,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_barang' => 'required|string|min:2',
            'harga_satuan' => 'required|integer',
        ]);

        Product::create([
            'nama_barang' => $validated['nama_barang'],
            'harga_satuan' => $validated['harga_satuan'],
        ]);

        flash('Data Produk berhasil ditambah!');

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit', [
            'product' => $product
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $validated = $request->validate([
            'nama_barang' => 'required|string|min:2',
            'harga_satuan' => 'required|integer',
        ]);

        $product->update([
            'nama_barang' => $validated['nama_barang'],
            'harga_satuan' => $validated['harga_satuan'],
        ]);

        flash('Data Produk berhasil disimpan!');

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        flash('Produk berhasil dihapus!');

        return back();
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Tambah Produk Baru</h1>

    <div class="row">
        <div class="col-lg-6">
            <form action="{{ route('product.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="nama_barang">Nama Barang</label>
                    <input value="{{ old('nama_barang' )}}" type="text" name="nama_barang" class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang">
                    @error('nama_barang')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="harga_satuan">Harga Satuan</label>
                    <input value="{{ old('harga_satuan' )}}" type="number" name="harga_satuan" class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan">
                    @error('harga_satuan')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Tambah</button>
            </form>
        </div>
    </div>

@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Edit Product</h1>

    <div class="row">
        <div class="col-lg-6">
            <form action="{{ route('product.update', $product->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="nama_barang">Nama Barang</label>
                    <input value="{{ $product->nama_barang }}" type="text" name="nama_barang" class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang">
                    @error('nama_barang')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="harga_satuan">Harga Satuan</label>
                    <input value="{{ $product->harga_satuan }}" type="number" name="harga_satuan" class="form-control @error('harga_satuan') is-invalid @enderror" id="harga_satuan">
                    @error('harga_satuan')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Simpan</button>
            </form>
        </div>
    </div>

@endsection

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Daftar Produk</h1>

    @include('flash::message')

    <form method="GET" action="/product">
        <div class="form-row d-flex align-content-end">
            <div class="col-md-7 mb-3">
                <label for="nama_barang">Nama Barang</label>
                <input name="nama_barang" value="{{ request('nama_barang') }}" type="text" class="form-control" id="nama_barang">
            </div>
            <div class="col-md-3 mb-3">
                <label for="harga_satuan">Harga</label>
                <input name="harga_satuan" value="{{ request('harga_satuan') }}" type="number" class="form-control" id="harga_satuan">
            </div>
            <div class="col-md-1 mb-3">
                <label for="operator">Operator</label>
                <select name="operator" class="custom-select" id="operator">
                    <option {{ request('operator') == '=' ? 'selected' : '' }} value='='>=</option>
                    <option {{ request('operator') == '>=' ? 'selected' : '' }} value=">=">>=</option>
                    <option {{ request('operator') == '<=' ? 'selected' : '' }} value="<="><=</option>
                </select>
            </div>
            <div class="col-md-1 mb-3">
                <label for="operator">&nbsp;</label>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col">
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar Pengguna</h6>
                    <div class="">
                        <a class="btn btn-success btn-circle btn-sm" href="{{ route('product.create') }}" role="button">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nama Barang</th>
                                    <th>Harga Satuan</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Nama Barang</th>
                                    <th>Harga Satuan</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @forelse ($products as $product)
                                <tr>
                                    <td>{{ $product->id }}</td>
                                    <td>{{ $product->nama_barang }}</td>
                                    <td>{{ rupiah($product->harga_satuan) }}</td>
                                    <td class="d-flex justify-content-center">
                                        <a class="btn btn-warning btn-circle btn-sm" href="{{ route('product.edit', $product->id) }}" role="button">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <form action="{{ route('product.destroy', $product->id) }}}}" method="post">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger ml-1 btn-circle btn-sm"
                                                onclick="return confirm('Yakin mau dihapus?');"
                                            >
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center" colspan="4">Tidak ada data yang ditemukan</td>
                                </tr>
                                @endforelse

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@push('styles')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                columnDefs: [
                    {
                        targets: 2,
                        className: 'text-right'
                    },
                    {
                        targets: 3,
                        className: 'text-center'
                    }
                ],
                "searching": false
                });
        });
    </script>
@endpush