routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function(){
    Route::get('/', App\Http\Controllers\DashboardController::class)->name('dashboard');
    Route::get('/transaction/{transaction}/export', App\Http\Controllers\ExportTransactionController::class)->name('transaction.export');
    Route::get('/transaction/{transaction}/print', App\Http\Controllers\PrintTransactionController::class)->name('transaction.print');
    Route::resource('transaction', App\Http\Controllers\TransactionController::class);
});

Route::middleware(['auth', 'admin'])->group(function(){
    Route::resource('product', App\Http\Controllers\ProductController::class);
    Route::resource('user', App\Http\Controllers\UserController::class);
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::query()
            ->when(!auth()->user()->isAdmin(), function($query){
                $query->whereDate('created_at', today());
            })
            ->when(request()->has('tanggal') AND ! empty(request('tanggal')) ?? false, function($query) {
                $query->where('created_at', 'LIKE', '%' . request('tanggal') . '%');
            })
            ->when(request()->has('nama_barang') AND ! empty(request('nama_barang')) ?? false, function($query) {
                $query->whereHas('products', function($query){
                    $query->where('nama_barang', 'LIKE', '%' . request('nama_barang') . '%');
                });
            })
            ->when(request()->has('total_harga') AND ! empty(request('total_harga')) ?? false, function($query) {
                $query->where('total_harga', request('operator'), request('total_harga'));
            })
            ->with('products')
            ->get();

        return view('transaction.index', [
            'transactions' => $transactions
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaction.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        return view('transaction.show', [
            'transaction' => $transaction,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->delete();

        flash('Transaksi berhasil dihapus!');

        return redirect()->route('transaction.index');
    }
}

resources/views/transaction/create.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Transaksi Baru</h1>

    @livewire('add-new-transaction')

@endsection

resources/views/transaction/export.blade.php
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Kasir</title>

<style type="text/css">
    * {
        font-family: Verdana, Arial, sans-serif;
    }
    table{
        font-size: x-small;
    }
    tfoot tr td{
        font-weight: bold;
        font-size: x-small;
    }
    .gray {
        background-color: lightgray
    }
</style>

</head>
<body>

    <table width="100%">
        <tr>
            <td valign="top"></td>
            <td align="right">
                <h3>Toko Berkah Bintang</h3>
                <pre>
                    Sehat untuk Ibadah
                    Jalan Suryakencana No. 34 Cisaat
                    085624028940
                </pre>
            </td>
        </tr>

    </table>

        <table>
                <tr>
                    <td>Transaksi #{{ $transaction->id }}</td>
                </tr>
                <tr>
                    <td>Waktu Transaksi : {{ $transaction->created_at->isoFormat('dddd, DD MMMM gggg hh:mm') }}</td>
                </tr>
        </table>

    <br/>

    <table width="100%">
        <thead style="background-color: lightgray;">
        <tr>
            <th>No</th>
            <th>Nama Barang</th>
            <th>Jumlah</th>
            <th>Harga Satuan</th>
            <th>Jumlah</th>
        </tr>
        </thead>
        <tbody>
            @foreach ($transaction->products as $product)
            <tr>
                <td scope="row" align="center">
                    {{ $loop->iteration }}
                </td>
                <td>
                    {{ $product->nama_barang }}
                </td>
                <td align="center">
                    {{ $product->pivot->jumlah }}
                </td>
                <td align="right">
                    {{ rupiah($product->harga_satuan) }}
                </td>
                <td align="right">
                    {{ rupiah($product->pivot->harga_satuan) }}
                </td>
            </tr>
            @endforeach
        </tbody>

        <tfoot>
            <tr>
                <td colspan="3"></td>
                <td align="right">Total Harga</td>
                <td align="right" class="gray">{{ rupiah($transaction->total_harga) }}</td>
            </tr>
        </tfoot>
    </table>

</body>
</html>

resources/views/transaction/index.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Daftar Produk</h1>

    @include('flash::message')

    <form method="GET" action="/transaction">
        <div class="form-row d-flex align-content-end">
            @if (auth()->user()->isAdmin())
            <div class="col-md-3 mb-3">
                <label for="tanggal">Tanggal</label>
                <input name="tanggal" value="{{ request('tanggal') }}" type="date" class="form-control" id="tanggal">
            </div>
            @endif
            <div class="col-md-4 mb-3">
                <label for="nama_barang">Nama Produk</label>
                <input name="nama_barang" value="{{ request('nama_barang') }}" type="text" class="form-control" id="nama_barang">
            </div>
            <div class="col-md-3 mb-3">
                <label for="total_harga">Total Harga</label>
                <input name="total_harga" value="{{ request('total_harga') }}" type="number" class="form-control" id="total_harga">
            </div>
            <div class="col-md-1 mb-3">
                <label for="operator">Operator</label>
                <select name="operator" class="custom-select" id="operator">
                    <option {{ request('operator') == '=' ? 'selected' : '' }} value='='>=</option>
                    <option {{ request('operator') == '>=' ? 'selected' : '' }} value=">=">>=</option>
                    <option {{ request('operator') == '<=' ? 'selected' : '' }} value="<="><=</option>
                </select>
            </div>
            <div class="col-md-1 mb-3">
                <label for="operator">&nbsp;</label>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col">
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
                <div class="card-header d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar Pengguna</h6>
                    <div class="">
                        <a class="btn btn-success btn-circle btn-sm" href="{{ route('transaction.create') }}" role="button">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Waktu Transaksi</th>
                                    <th>Produk</th>
                                    <th>Total Harga</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Waktu Transaksi</th>
                                    <th>Produk</th>
                                    <th>Total Harga</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @forelse ($transactions as $transaction)
                                <tr>
                                    <td>{{ $transaction->id }}</td>
                                    <td>{{ $transaction->created_at->isoFormat('dddd, DD MMMM gggg hh:mm') }}</td>
                                    <td>
                                        @foreach ($transaction->products as $product)
                                            <span>{{ $product->nama_barang }}{{ ! $loop->last ? ', ' : '' }}</span>
                                        @endforeach
                                    </td>
                                    <td>{{ rupiah($transaction->total_harga) }}</td>
                                    <td class="d-flex justify-content-center">
                                        <a class="btn btn-warning btn-circle btn-sm" href="{{ route('transaction.show', $transaction->id) }}" role="button">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a class="btn btn-info btn-circle btn-sm ml-1" href="{{ route('transaction.export', $transaction->id) }}" role="button">
                                            <i class="fas fa-file-download"></i>
                                        </a>
                                        <form action="{{ route('transaction.destroy', $transaction->id) }}}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger ml-1 btn-circle btn-sm"
                                                onclick="return confirm('Yakin mau dihapus?');"
                                            >
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center" colspan="5">Tidak ada data yang ditemukan</td>
                                </tr>
                                @endforelse

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection

@push('styles')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                columnDefs: [
                    {
                        targets: 3,
                        className: 'text-right'
                    },
                    {
                        targets: 4,
                        className: 'text-center'
                    }
                ],
                'searching': false,
                'order':[
                    [0,'DESC']
                ]
                });
        });
    </script>
@endpush

resources/views/transaction/print.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Receipt example</title>
        <style>
            * {
                font-size: 12px;
                font-family: 'Times New Roman';
            }

            td,
            th,
            tr,
            table {
                border-top: 1px solid black;
                border-collapse: collapse;
            }

            td.description,
            th.description {
                width: 110px;
                max-width: 110px;
            }

            td.quantity,
            th.quantity {
                width: 20px;
                max-width: 20px;
                word-break: break-all;
            }

            td.price,
            th.price {
                width: 100px;
                max-width: 100px;
                word-break: break-all;
            }

            .centered {
                text-align: center;
                align-content: center;
            }

            .right {
                text-align: right;
                align-content: right;
            }

            .ticket {
                width: 155px;
                max-width: 155px;
            }

            @media print {
                .hidden-print,
                .hidden-print * {
                    display: none !important;
                }
            }
        </style>
    </head>
    <body onload="window.print()">
        <div class="ticket">
            <p class="centered">TOKO BERKAH</p>
            <p class="centered">
                Transaksi #{{ $transaction->id }}
                <br>{{ $transaction->created_at->isoFormat('DD/MM/Y hh:mm') }}
            </p>

            <table>
                <thead>
                    <tr>
                        <th class="quantity">#</th>
                        <th class="description">Produk</th>
                        <th class="quantity">Q</th>
                        <th class="price right">Harga</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transaction->products as $product)
                    <tr>
                        <td class="quantity centered">{{ $loop->iteration }}</td>
                        <td class="description">{{ $product->nama_barang }}</td>
                        <td class="quantity centered">{{ $product->pivot->jumlah }}</td>
                        <td class="price right">{{ rupiah($product->pivot->harga_satuan) }}</td>
                    </tr>
                    @endforeach
                    <tr>
                        <th class="description right" colspan="3">TOTAL</th>
                        <th class="price right">{{ rupiah($transaction->total_harga) }}</th>
                    </tr>
                </tbody>
            </table>
            <p class="centered">Terima kasih</p>
        </div>
    </body>
</html>

resources/views/transaction/show.blade.php
@extends('layouts.master')

@section('content')
    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Transaksi #{{ $transaction->id }}</h1>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <p>Waktu Transaksi : {{ $transaction->created_at->isoFormat('dddd, DD MMMM gggg hh:mm') }}</p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Product</th>
                            <th class="text-center" scope="col">Jumlah</th>
                            <th class="text-right" scope="col">Harga</th>
                            </tr>
                        </thead>
                        <tbody>
                           @foreach ($transaction->products as $product)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $product->nama_barang }}</td>
                                <td class="text-center">{{ $product->pivot->jumlah }}</td>
                                <td class="text-right">{{ rupiah($product->pivot->harga_satuan) }}</td>
                            </tr>
                           @endforeach
                           <tr>
                            <td class="font-weight-bold text-right" colspan="3">Total Harga</td>
                            <td class="font-weight-bold text-right">{{ rupiah($transaction->total_harga) }}</td>
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


@endsection